### PR TITLE
Increased timeout on tests from 30 to 120 seconds...

### PR DESCRIPTION
**Pull request by mmcc007**
… for slow running emulators in cloud

Fixed analyzer warnings

The following jobs are timing out (and succeeding on retry):
firestore_redux_android
mvc_android
mvi_flutter_android
simple_bloc_flutter_android
vanilla_android

### CODE REVIEW

**Comment by mmcc007** [comment]
Huh, not a great result, mvc_android is still timing out (and succeeding on retry). May have to look into this further.

**Comment by mmcc007** [comment]
Reopened https://github.com/flutter/flutter/issues/28811

**Comment by brianegan** [comment]
@mmcc007 Could you please resolve the conflict here?

**Comment by brianegan** [comment]
Thanks @mmcc007! Is this one ready to merge?

**Comment by mmcc007** [comment]
There seems to be somewhat inconsistent behavior in integration tests since the new 'logs-in-place-of-timeouts' feature was introduced in more recent flutter versions. The tests I ran, a week or so ago, were consistently running slower on first try, hitting the default per test timeout of 30 seconds, and then passing on second try (this is new behavior). Suggests some kind of tuning issue related to the new feature and possibly related to the way dependencies are being cached on travis, or some transient condition on travis (which seems to be happening more often than expected). 

May try a more recent release of flutter and change way dependencies are being cached, or a few other things before merging... it's looking more like the increased timeout is not buying much... 

It's not a blocker as recents builds seem to be behaving better (other than travis transient behavior). So for now, rather than merging, I'm ok with closing this PR while experimenting with options and then reopen later if needed.

**Comment by brianegan** [comment]
Sounds good! Just wanted to check in and see if I could help out here :) If you'd like to keep it open and keep trying stuff or close it out -- no worries at all. 

Please let me know if / when I can help out!

**Comment by mmcc007** [comment]
I think I'll close this PR (was hoping for a simple fix and when running on fork it did not timeout -- turns out that was just plain luck 😂).
 
Since #125 we know more about why builds are timing out. A potential fix is on the way from Dart team (dart-lang/sdk#33838... at least for some timeouts).

If the dart fix helps stabilize the build, then can get back to finding ways to run tests faster in CI. (the remaining timeouts probably have more to do with the competing resources in the shared CI build environment, slow running emulators, etc..).

**Pull request closed without merging**
