### PR TITLE
Added integration test to create a new task

### PR DESCRIPTION
**Pull request by mmcc007**
Modified new task screen for redux project. The new task screen for other projects probably need to be modified.

Runs the integrations test on ios in travis

### CODE REVIEW

**Comment by brianegan** [comment]
Oh wow -- I wasn't able to get the integration tests running on Travis last time I tried -- I ran into Out of Memory errors. Did this setup work!? If so, massive kudos :)

**Comment by mmcc007** [comment]
The one failing job should pass if u resubmit the job. Here is the same code with all the jobs passing:
https://travis-ci.org/mmcc007/flutter_architecture_samples/builds/439978568.

codecov.io was down during the build (what are the odds!) so it may have missed the report. Could try resubmitting the unit test job to see if the result appears here.

All the red x's next to the commits, other than for bad builds, are due to the reduction in code coverage of 0.12%!

Other than that it looks good to me!

**Comment by brianegan** [comment]
Great, thanks again for such a good contribution :) I'm so happy we can run these tests on CI now!

Once the tests go green, I'll merge it up (might be tomorrow morning if they take a bit).

**Comment by mmcc007** [comment]
No prob, it was a great learning experience. Maybe some day we can demo deploying one of the apps to both of the stores with a tagged release or something. That would be cool.

The build succeed this time, so should be good to go 👍

**Comment by mmcc007** [comment]
Hey... I have a PR I can start for #79. If this one is good to go I can start the other one

**Comment by brianegan** [comment]
Thanks @mmcc007! That was my bad -- I read the CodeCov report as a failure rather than a very small reduction in coverage.

I've merged this up! Please feel free to submit a PR for #79 :)

**Pull request merged**
