### PR TITLE
Reorganization - Part 2 

### PR DESCRIPTION
**Pull request by groksrc**
This is Part 2 of the changes proposed in #101. See also #104.

Specifics in this change:
* All of the projects that were formerly in `/example` are moved up to the root of the project
* The build scripts and related files are adjusted to look for the files in the new location
* READMEs and index.html are adjusted to remove the example directory from the paths

This PR was branched from the `todos_app_base` branch created in #104, so there are a couple of options for merging. One would be to accept #104 into master, which should shrink this diff. Another would be to merge this PR and drop #104. I'm open to suggestions.

Also, I'm not sure why but GitHub has picked up most of the changes as moves but a few as new files. None of the source code was changed in this PR so there should not be any new files reflected, but there are.  From the project root these are the commands executed to begin the change:
```
$ git mv example/* .
$ rm -rf example
```
After that I did a search and replace to update the pubspec.yaml files to refer to the new path for the `todos_app_core` project, then updated the READMEs and index.html.

### CODE REVIEW

**Comment by brianegan** [comment]
Hey there -- looking great so far! The only concern I've seen is wrt this PR. Do you know why it might have deleted the old files and created new files instead of just doing a regular move? I replicated the command you posted above and came out with this PR, which includes 0 additions / deletions, just the move: https://github.com/brianegan/flutter_architecture_samples/pull/108

My biggest concern: If all of these files are deleted & recreated instead of moved, we will lose all of the git history. I can understand it might be a pain, but I'd really rather avoid that if possible!

**Comment by groksrc** [comment]
Oh good point. I don't want to lose the history either, I'll try to recreate this PR without the new file problem. 👍

**Comment by brianegan** [comment]
Really appreciate it :) Thanks!

**Comment by groksrc** [comment]
Closed in deference to #110

**Pull request closed without merging**
