### PR TITLE
Refactor scoped_model to be more scoped_modelly

### PR DESCRIPTION
**Pull request by passsy**
Based on my current knowledge of `scoped_model` I refactored this todo app based on PR #8.

Changes:
- `AppState` and `StateContainer` are now one thing -> `TodoListModel`, wrapping the application.
- `Detail` and `Edit` will be started with the `Todo` `id` instead of the complete `Todo` object, loading it afterwards from the `TodoListModel`.
- `Todo` is now immutable. Use `.copy()` to change the content.
- Instead of passing all lambdas into `ExtraActionsButton` and `FilterButton` they now communicate directly with `TodoListModel`. This reduces the logic in `HomeScreenState#build`.
- `HomeScreen` doesn't wrap the `Scaffold` in `ScopedModelDescendant`. This should improve the performance. The `HomeScreen` logic contains now nothing more than conducting the tabs and action items. All logic regarding the todo list items is now deeper in the Widgets.
- The `HomeScreen` was triggering the loading of data from the repository. This is now the responsibility of the `TodoListModel` when a new listener gets added (see `addListener`). This could be improved by checking the listener count.

### CODE REVIEW

**Comment by brianegan** [comment]
Amazing, thanks so much! Lemme give it a review :)

**Comment by brianegan** [comment]
Really appreciate the work! Would love to chat about a few points, as they're things I've faced / wondered about when developing these apps. Interested in your thoughts as well :)

  * Combine `AppState` and `StateContainer` -- I tried this out as well, but was on the fence as to which approach was better. Good to have a second opinion, let's keep em together!
  * What do you think about the advantages / disadvantages of making `Todo` immutable? In some architectures (Redux) it fits the pattern, but for `scoped_model` and regular `StatefulWidget`s, it felt like it made the app a bit more complex. I felt like those architectures worked better with mutable values. Why? Once `Todo` is immutable, you need to pass an `id` to the `Detail` and `Edit` screens instead of the `Todo` directly. Then, you also need to create a function to look up `Todos` by id. On the `Delete` screen, this will cause an interesting problem -- after the `Todo` is deleted, the function will return null and you fall back to `new Todo('');`, which means the UI shows a blank `Todo` as the screen animates away. While it's not a huge detail, I see it as an interesting case because it shows where Reactive, Immutable Models need some care when interacting with Flutter. If Todos were mutable, you'd be able to pass the instances directly to the Edit and Detail screens, and wouldn't run into the issue with animations, for example. What are your thoughts?

Thanks again! One final, unrelated question:

Do you think I should move this repo to a new Github org? Would that make you more comfortable contributing? (I'll add your name to the Readme for sure)

**Comment by passsy** [comment]
#### Immutable Todo

Previously, to change the check state, the container does the actual change (`container.updateTodo(todo, complete: !todo.complete);`). The container first changes the data, then notifies the listeners and sends the changes to the repository.

Two things could go wrong:
- Wrong usage for updates: One could call `todo.complete = !todo.complete` without calling the container. This would work in some cases when `build` gets called due to another change but it bypasses possible validation logic in the `container`. An immutable `Todo` forces anyone to use the container.
- Missing subscription, implicit subscriber: With a reference to the mutable object it's not required to use a `ScopedModelDescendant` to get updates. Any `setState` updates the UI and could show it correctly (by accident without explicit subscription). The `ScopedModel`, without real subscribers, could for example stop polling changes from remote because it thinks nobody is interested in the data.

#### Detail view and edit could be a named routes:

When working with ids instead of PODOs to pass content around named routes can be used. Currently creating a new todo and editing an existing one requires to different ways to push the same `AddEditScreen`.
```dart
// add Todo, pushes AddEditScreen with todo == null
Navigator.pushNamed(context, ArchSampleRoutes.addTodo);

// edit Todo
Navigator.of(context).push(
  new MaterialPageRoute(
    builder: (context) {
      return new AddEditScreen(
        todo: todo,
        key: ArchSampleKeys.editTodoScreen,
      );
    },
  ),
);
```
Both cases should use `Navigator.pushNamed`, as well as the detail view. It helps later on with deep linking.

#### Deleting the todo before the exit animation ends

This problem was quite hard and unexpected. I'm not happy with my current solution. I should show an empty container or a centered "Not found/Deleted" text if the `Todo` was deleted instead of creating a new empty `Todo`. This would also cover the case someone starts this route with an invalid `Todo` `id`.

The correct solution would be to keep the `Todo` in the model, marked as deleted, and wait some time before actually deleting it (after the snackbar disappeard). Maybe in my next PR.

--- 

Currently I don't care where this repo is located. In the long term I see it [here](https://github.com/googlesamples/) analog to [android-architecture](https://github.com/googlesamples/android-architecture)

**Comment by brianegan** [comment]
Hey, sorry for the delay. Busy one! Very interesting points, thanks so much for sharing those insights...

**Immutable Values**

Hrm, tricky one indeed -- I definitely see your points. Making it immutable indeed forces the user to call up to the parent function, which will ensure the right call is made and that subscribers 

What would you think about turning the `Todo` class into a `scoped_model` as well? Then the `Detail` page and `Edit` page could use `ScopedModelDescendant<Todo>`?

The user could then use mutable values (which call `notify` on the `set` methods), and the Screens would be updated properly? It would also solve the null on deletion problem....

Might just give that a whirl to see what it's like.

**Deep Linking**

Good call -- I've thought about making handling a `/detail/:id` route a requirement of the app, because of the importance of deeplinks.

If the `Todo` as `Model` idea from above works, I could see a path toward supporting this functionality by keeping the `getTodoById` function.

**Deleting the todo before the exit animation ends**

Yah, I was surprised by this problem as well :D Tough one to solve in some frameworks...

** Repo location **

Cool, I'll keep it here for now...

** Thanks again! Really appreciate everything!!! **

**Comment by brianegan** [comment]
Hey hey :)

As a thought experiment, I changed the `Todo` into a `TodoModel` to see if that might feel like a cleaner API. I think some things are better, others are worse. Would love to hear your opinion!

  * `TodoItem`, `AddEditScreen`, and `DetailsScreen` no longer accept a `Todo` or `todoId`. They are now wrapped in a `ScopedModel<Todo>`, and must use a `ScopedModelDescendant<Todo>` in the `build` method to get the `Todo` the Widgets require. 
  * The `Todo` is once again mutable, but replaced by `get` and `set` methods. The `set` methods set the value and then perform a `notifyListeners()` so the Widgets are rebuilt.
  * The `todo_list` listens for changes on all `Todos`. If a change is made to a `Todo`, the change will be stored in localstorage.
  * For funzies, wrote a named Detail route just to be sure that would work.

Benefits:

  * Both `TodoListModel` and `TodoModel` have mutable interfaces (consistency)
  * You can now do a simple `todo.complete = !todo.complete` and your Widget will update!
  * Fixes the problem with `Todo` screen being blank upon Deletion from the Detail page

Drawbacks:

  * Still nothing preventing you from just passing a `todo` or `todoId` and forgetting to use a subscriber...
  * Not sure if this would be perceived as easier to understand, or is still prone to the mistakes you mention (forgetting to subscribe)

https://github.com/brianegan/flutter_architecture_samples/commit/c5ad8a5fa66def865e14371684b40b79c5b05879

**Comment by passsy** [comment]
Interesting, I think I understand your intention although I don't agree with making `Todo` a  `TodoModel`.

Let's get back to what a `Model` is:
```dart
/// Base class for classes that provide data via [InheritedWidget]s.
abstract class Model {
```

A `Model` provides data but it is not the data itself. By changing the immutable PODO `Todo` to a `TodoModel` we again lose layers. I strongly belief Entities are very valuable in every architecture and shouldn't be mixed with higher layers such as UseCases or Controllers.

This combination already introduced an [odd case](https://github.com/brianegan/flutter_architecture_samples/commit/c5ad8a5fa66def865e14371684b40b79c5b05879#diff-c9272b16ab5a59d67e3772c6aa1da18cR40):
The `ListView` listens to `TodoListModel` and the items are wrapped in `ScopedModel<TodoModel>` also listening for changes. A single item will never rerender alone. The `itemBuilder` will be called already for every change.

What I really like about you change is that you end up with one Model per Screen as described [here](https://medium.com/@mehmetf_71205/inheriting-widgets-b7ac56dbbeb1):

> **Properly scope your inherited widgets**
>Inherited widgets are placed at the root of a widget tree. That, in effect, becomes their scope. In our team, we found that the power to declare context anywhere in the widget tree is a bit too much. So, we restrict our context widgets to accept only Scaffold (or its derivatives) as a child. That way, we ensure the most granular context can be at the page level ending up with two types of scope:
> - App-scoped widgets such as MediaQuery. These are accessible by any widget on any page in your app since they sit at the root of your app widget tree.
> - Page-scoped widgets such as the MyInheritedWidget in the example above.

When I started with refactoring, I also created a model for each screen and wrapping screens in that model before pushing a Route. I worked but I ended up with tons of duplicated code because the functionality of all screens is so similar. Instead of extracting logic in reusable components (UseCases) I promoted the `TodoListModel` to be an App-scoped `Model`, accessible by everyone.
 
If there would be a different functionality such as inviting other users to my list, I would create a `Model` for that screen which requires logic the rest of the app won't ever use.

Instead of a global TodoListModel I could think about this: 
- keep the immutable `Todo` and use it to show data on the screen.
- create a `TodoModel` with CRUD methods changing a *single* `Todo` and sync it directly with the repository. (`Id` in constructor, no access to other Todos)
- Use `TodoListModel` to sort the list and remove update and delete. Right now the TodoDetail page could change the list ordering. 
- Create a `StatsCounterModel` calculating the stats by getting data from the repository

This would create some code duplication but will be a better guidance how scoped_model can be used in larger applications.

**Comment by brianegan** [comment]
Guten Morgen :) Thanks again for taking the time to work through this with me. Really appreciate it!

Overall, I think the changes you propose in the end make a lot of sense. Could we dig just a bit deeper on one point for clarity?

"A Model provides data but it is not the data itself. By changing the immutable PODO Todo to a TodoModel we again lose layers."

I think agree on this point, but I believe I misunderstood your original change set a bit, and therefore extended your approach in the wrong way. Originally, I was trying to follow a layered pattern you describe and create by having two classes: `AppState`, which was a PODO that holds the logic and a and a separate `Model` called `StateContainer` that interacted with the PODO. In your PR you combined the two into a `TodoListModel`.

Could you describe the reasoning behind combining the two a bit more? The reason I thought you might have done it was to remove code duplication (similar to the code duplication you talk about at the end of your comment).

**Pull request merged**
