### PR TITLE
Add ReduRx sample

### PR DESCRIPTION
**Pull request by leocavalcante**
Borrowed a lot from vanilla and built_redux, but I think the main differences are clear, like: where and how Actions can be called and specially how sub-state/props are mapped from State to a Widget builder.

### CODE REVIEW

**Comment by leocavalcante** [comment]
Working on tests!

**Comment by mmcc007** [comment]
If you have lcov installed you can run something like:
```
genhtml lcov.info -o coverage --no-function-coverage
```
to get a coverage report locally

**Comment by brianegan** [comment]
Thanks for the PR! Sorry, I've got family visiting this week and haven't had as much time to review. I'll try to take some time to go through it in the next couple of days, but might not get to it until next weekend.

Thanks again, great contribution :)

**Comment by leocavalcante** [comment]
No problem at all, take the time you need, meanwhile I'll be trying to decrease the coverage decrease 😄

**Comment by brianegan** [comment]
Hey there -- just had a look! Overall, clean and simple implementation. Nice one :)

Feedback:

  [ ] I took a look at the coverage report, and since a lot of the code coverage loss is from generated files, I don't think we should worry too much about it. What you have seems good to me! 
  [ ] The app isn't persisting changes locally when todos are first fetched, added, removed, edited, etc. When you perform a Hot Restart, it grabs the Todos from the Mock Web Service once more. Could you please change the app to load the latest state of the todos from local storage?
  [ ] Could you please add a bit more information to the app's README? I think you've written a couple of articles on this library. No need to repeat everything you said there, but maybe a bit more info about flutter_redurx or links to that info.
  [ ] Please add your app to the `index.html` file found in the root of the project
  [ ] If you'd like, but this is a great contribution. Please feel free to add yourself to the Contributors list on the `index.html` and `README.md` files in the root of the project.
  [ ] Rando question: Are there any special tricks needed to test the Widgets for your lib? Is that particularly easy or difficult? I didn't see anything out of the ordinary, but just wanted to ask.

Thanks again, amazing contribution :)

**Comment by leocavalcante** [comment]
Hi @brianegan 
Thank you very much for the feedback.
I added your appointments and answering you question: there is no special treatment to test the Widgets, they are composed inside the `Connect` like it would be on any `WidgetBuilder`, but with its sub-state instead of a `context`, this sub-state can be freely mocked as simple plain-old Dart code.

**Comment by brianegan** [comment]
Thanks again @leocavalcante! Looks great :) I'll go ahead and merge!

One quick note: I'm going to slightly change the "differences" section of the README so it's it's a neutral voice and to describe the differences without any "subjective" statements (since in my eyes `flutter_redux` is also just a wrapper around a `StreamBuilder`, but I don't think it's worth diving into a lengthy discussion of why we each perceive our own libraries that way :)

**Comment by leocavalcante** [comment]
Awesome, thanks! People often asks me for a more complex example of ReduRx, this is a great showcase.

**Pull request merged**
