### PR TITLE
Extract FirestoreServices as Repository

### PR DESCRIPTION
**Pull request by brianegan**
Heya @kinggolf :)

I wanted to reuse the Firebase stuff on another sample and make it easier to share repositories across platforms (web and Flutter), so I decided to extract it out as a `ReactiveTodosRepository`. 

This required a few changes:

  1. Rename `FirebaseServices` to `FirebaseUserRepository` and `FirestoreReactiveTodosRepository`. `FirebaseUserRepository` allows users to log in. `FirestoreReactiveTodosRepository` streams the todos from Firestore.
  2. Update the Middleware of the app. They now send the correct updates to Firestore and dispatch actions every time the data changes on Firestore. 
  3. Dispatch actions to Log in / Start listening to data rather than calling Firestore directly.
  4. Updated the integration tests to work with these new Repositories, pass them through as part of the `main` function to reduce a bit of duplication.

Whatcha think?

### CODE REVIEW

**Comment by kinggolf** [comment]
Hi @brianegan, I think this makes good sense for the repo, both the motivation and the architectural improvements. LGTM - thanks for spending your time on this.

**Comment by brianegan** [comment]
Thanks for checking it out @kinggolf! I'll go ahead and merge and hopefully get another Firebase example up in the next week or two :)

**Comment by kinggolf** [comment]
@brianegan I double checked the updated repo today by cloning the project to my local and going through the Readme steps, just like starting a new project. Everything works - Android, iOS, and all tests. Good job. I'm still digging into some of your updates to see where I can make improvements to my current projects - just trying to learn and follow best practices.

I feel this Redux implementation is very similar to what Paolo presented:
1) UI Components, 'presentation' folder, are quite simple and have no business logic,
2) Business logic resides in the 'containers' and above,
3) Redux is naturally a reactive pattern,
4) How much of this code could be applied to an AngularDart web app? Good question! Other than rewriting UI widgets into component templates, I guess 'flutter-redux' would need to be removed but connecting the templates to reactive data input should be straightforward.
Seems like it would be a fun exercise, but I suspect more than 50% of the current code would require re-writing.

**Comment by brianegan** [comment]
Yep! Overall, in order to work on both Web and Flutter, this is a pretty "natural" refactoring: Provide an abstract Data Layer: The Repository, then concrete implementations of that Repository for both Web and Flutter.

The Domain Layer (Redux or Bloc or any other pure-Dart lib) works with the Abstract Repository. When you create the Redux Middleware or Block, you provide a concrete implementation depending on the environment.

How much needs to be rewritten? This is definitely an interesting question! It's the exact experiment I want to run :) The next steps:

  1. Create a Web version of the `ReactiveTodosRepository`
  2. Create a `redux_core` library that is pure-Dart that uses the `TodosRepository`. It will include the Reducers, Actions, Middleware and Selectors. Perhaps even ViewModels.
    - Use this for the firestore_redux app.
    - Use this for an Angular app
  3. Create a `bloc` library that's also Pure Dart. 
    - Use this for the redux app.
    - Use this for an Angular app

**Pull request merged**
