### PR TITLE
Add Widget Tests to Bloc Library Sample

### PR DESCRIPTION
**Pull request by felangel**
**Addresses: #119** 
screen shot 2019-03-06 at 8 16 46 pm

**Note: Coverage isn't 100% because of some weird LCOV behavior:**
screen shot 2019-03-06 at 8 15 03 pm

### CODE REVIEW

**Comment by brianegan** [comment]
Wow, this is an amazing PR! I was hoping for one or two tests as a demonstration haha, but this is so thorough and so good.

Again, thank you so much for contributing! I really think these types of tests can offer a really helpful guide for folks working on "production level" apps.

**Comment by brianegan** [comment]
One last thing: In addition to updating the README, could you please update the `index.html` page as well with your app and name? The index.html gets deployed to `fluttersamples.com`.

Sorry I forgot to mention those two in the original PR!

**Comment by felangel** [comment]
Haha thanks! I  tried to be as thorough as possible 😄 and oops... I’ll update the index.html in the next hour 👍

**Comment by felangel** [comment]
@brianegan just updated the `index.html` 👍

**Comment by brianegan** [comment]
Perfect, thanks!

**Comment by felangel** [comment]
@brianegan looks like the integration tests for certain libraries are failing. Do you know if those were already failing or did I break something? (I don't think my changes impacted any other samples)

**Comment by mmcc007** [comment]
@felangel looks like a problem on Travis. I restarted the failing job, so it should pass now.🤞

**Comment by felangel** [comment]
@mmcc007 thanks! 💯

**Pull request merged**
