### PR TITLE
 Workaround for built_redux build problem

### PR DESCRIPTION
**Pull request by mmcc007**
Also added codecov report

Not clear how the build_runner is generating files, so bypassed for now. Should prob be resolved when known how.

### CODE REVIEW

**Comment by brianegan** [comment]
Cool, thanks for the PR! One Q: Is CodeCov necessary? Definitely happy to have a coverage reports, but didn't want to confuse folks with 2 badges that show the same info

**Comment by mmcc007** [comment]
I added codecov only for the opportunity to evaluate the different analysis (not having integrated codecov myself in the past)

It looks like codecov scans the directories for lcov.info files by default, so no need to massage multiple lcov.infos into one as required for coveralls. The different reporting styles, looks like codecov does slightly better. Not sure which supports more advance features, like branch coverage, complexity, etc..

But in the end it is entirely up to you. Either way I'm happy to make the change.. ur call .. just let me know, thnx 👍

**Comment by brianegan** [comment]
Nice, thanks again for helping out :) Glad to see there's a new version of `flutter_built_redux`!

If CodeCov is simpler to maintain, let's go that route. Less to think about when adding new projects :)

**Comment by mmcc007** [comment]
Yep, no prob :)

This fixes #69.

The remaining issue is how to run the build_runner for built_redux in a dart 2.0 world. It's no longer regenerating the *.g.dart files, whereas the mvu project is.

**Comment by mmcc007** [comment]
AFAIK: this should be ok to commit. Looks like the build_runner thing should prob be a separate issue.

**Comment by brianegan** [comment]
Hey @mmcc007 -- sorry was on vacation and came back to a bunch of work. My bad on dropping the ball here. Is this one good to go?

**Comment by mmcc007** [comment]
no prob at all... should be good to go 👍

**Comment by brianegan** [comment]
Excellent, thanks again :)

**Pull request merged**
