### PR TITLE
MobX example

### PR DESCRIPTION
**Pull request by pavanpodila**

### CODE REVIEW

**Comment by pavanpodila** [comment]
@brianegan The tests are all passing. Seems like a glitch here in the CI ?

**Comment by brianegan** [comment]
Thanks @pavanpodila! I'm taking a look and should have a review done in the next day or so :)

**Comment by pavanpodila** [comment]
Awesome! Look forward to it @brianegan

**Comment by brianegan** [comment]
Heya @pavanpodila -- this is really cool overall! Thanks for sharing :)

I think what you've got is a really good start, but feels a bit incomplete in some regards when looking at the app spec.

I wanted to play with MobX a bit more, so I'm working on adding the following features and will push up the changes shortly for your review.

**Comment by pavanpodila** [comment]
Thanks Brian! Let me know what is incomplete. I'm happy to take it up. Of course, I won't take away the joy of using **MobX** from you 😄

**Comment by brianegan** [comment]
Yah, had a few hours of fun :) Just pushed up #166 -- please let me know what you think of the changes!

**Comment by brianegan** [comment]
Thanks again! I've merged all of these into the updated version which is now merged into master :)

**Comment by pavanpodila** [comment]
Awesome Brian! Thanks for cleaning up lot of the code 👍. Curious to hear if you had any pain points using MobX :-)

**Comment by brianegan** [comment]
Absolutely -- thank you! 

Overall, the experience was really nice. In the end, this sample is one of the smallest in terms of LOC (minus generated files), was really easy to test, and I'm excited by the extension methods on Streams and how easy those are to now interop with the Extensions provided by RxDart -- I tried my small "Github Search App" from the RxDart repo with Mobx and it was as easy as using all the normal operators then popping an `asObservable` at the end of the chain. Way cool!

My biggest pain points:
  1. No `toString`, `==` and `hashCode` generation. Those are really important for testing and I think they should be generated automatically -- I had to generate them using IntelliJ.
  2. The way the Store is defined makes adding custom constructors pretty painful. For example, I wanted to add the `toEntity` method and `fromEntity` static method to the `Todo` class. It was easy enough with the `toEntity`, but adding `fromEntity` was not fun (redirecting constructor, etc). In the end, I went with the `Codec` instead. I'm sure you've tried many options for how to make the code generation work and found this was the best approach, but it's definitely a pain point.

**Comment by pavanpodila** [comment]
Thanks Brian!

For **1**. we discussed about auto-generating that and will take it on priority. Not sure if there is a quick and easy way to generate `hashCode` though.

For **2**. this is the best we could do in terms of codegen and still allowing extension from the outside. We explored the use case of generating a public class in the codegen but ran into lots of issues with extensibility. For now this is the best compromise. I am sure this will improve as Dart gets better facilities and language features.

**Pull request closed without merging**
